//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotPlanet.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotPlanet.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} laeb, nüüd {1}%. Tolmuimeja nurrub..
        /// </summary>
        internal static string Cleaner_Charge_Ok {
            get {
                return ResourceManager.GetString("Cleaner_Charge_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tahab korraldada üldpuhastuse, kuid akut ei jätku..
        /// </summary>
        internal static string Cleaner_Crazy_LowBattery {
            get {
                return ResourceManager.GetString("Cleaner_Crazy_LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} küürib end nii põhjalikult, et pesi oma värvi maha! Aku: {1}, terviklikkus: {2}..
        /// </summary>
        internal static string Cleaner_Crazy_Ok {
            get {
                return ResourceManager.GetString("Cleaner_Crazy_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: akut on liiga vähe, harjased longus kurvalt alla..
        /// </summary>
        internal static string Cleaner_DoWork_LowBattery {
            get {
                return ResourceManager.GetString("Cleaner_DoWork_LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} koristab põrandat. Aku: {1}..
        /// </summary>
        internal static string Cleaner_DoWork_Ok {
            get {
                return ResourceManager.GetString("Cleaner_DoWork_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aku laetus peab olema vahemikus 0–100..
        /// </summary>
        internal static string Err_Invalid_battery {
            get {
                return ResourceManager.GetString("Err_Invalid_battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikaator peab olema vahemikus 0–999999..
        /// </summary>
        internal static string Err_Invalid_id {
            get {
                return ResourceManager.GetString("Err_Invalid_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terviklikkus peab olema vahemikus 0–100..
        /// </summary>
        internal static string Err_Invalid_integrity {
            get {
                return ResourceManager.GetString("Err_Invalid_integrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi peab olema 2–20 märki pikk ega tohi olla tühi..
        /// </summary>
        internal static string Err_Invalid_name {
            get {
                return ResourceManager.GetString("Err_Invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ühendus päikesega. Aku: {1}%..
        /// </summary>
        internal static string Explorer_Charge_Ok {
            get {
                return ResourceManager.GetString("Explorer_Charge_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unistab uue planeedi avastamisest, kuid unistusteks akut pole..
        /// </summary>
        internal static string Explorer_Crazy_LowBattery {
            get {
                return ResourceManager.GetString("Explorer_Crazy_LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} avastas uue planeedi! Selgus, et see on tema enda vari. Aku: {1}..
        /// </summary>
        internal static string Explorer_Crazy_Ok {
            get {
                return ResourceManager.GetString("Explorer_Crazy_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on ekspeditsiooniks liiga väsinud..
        /// </summary>
        internal static string Explorer_DoWork_LowBattery {
            get {
                return ResourceManager.GetString("Explorer_DoWork_LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} uurib ümbrust. Aku: {1}..
        /// </summary>
        internal static string Explorer_DoWork_Ok {
            get {
                return ResourceManager.GetString("Explorer_DoWork_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} skaneerib säästurežiimis: näeb vaid kolme pikslit..
        /// </summary>
        internal static string Explorer_Scan_LowBattery {
            get {
                return ResourceManager.GetString("Explorer_Scan_LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} skaneerib ümbrust: leitud {1} kivi ja {2} kahtlane vari..
        /// </summary>
        internal static string Explorer_Scan_Ok {
            get {
                return ResourceManager.GetString("Explorer_Scan_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} arreteeris oma varju! Vari osutas vastupanu, terviklikkus: {1}..
        /// </summary>
        internal static string Guard_Crazy_Ok {
            get {
                return ResourceManager.GetString("Guard_Crazy_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} jäi vahipostil tukkuma. Norskab mikrofoni..
        /// </summary>
        internal static string Guard_Crazy_Sleep {
            get {
                return ResourceManager.GetString("Guard_Crazy_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} patrullib territooriumi. Reaktor mühiseb, laadimist pole vaja..
        /// </summary>
        internal static string Guard_DoWork {
            get {
                return ResourceManager.GetString("Guard_DoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} skaneerib perimeetrit: kõik on kontrolli all, välja arvatud sina. Kahtlane..
        /// </summary>
        internal static string Guard_Scan {
            get {
                return ResourceManager.GetString("Guard_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: vigane laadimiskogus ({1}), olek jäi muutmata..
        /// </summary>
        internal static string Msg_Charge_Invalid {
            get {
                return ResourceManager.GetString("Msg_Charge_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} laeb. Aku: {1}%..
        /// </summary>
        internal static string Repair_Charge_Ok {
            get {
                return ResourceManager.GetString("Repair_Charge_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on valmis kõike järjest parandama, kuid aku sai tühjaks..
        /// </summary>
        internal static string Repair_Crazy_LowBattery {
            get {
                return ResourceManager.GetString("Repair_Crazy_LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parandab kõike, mida näeb, isegi töökorras asju! Lõhkus ka ennast pisut. Aku: {1}, terviklikkus: {2}..
        /// </summary>
        internal static string Repair_Crazy_Ok {
            get {
                return ResourceManager.GetString("Repair_Crazy_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} laguneb ise koost ega saa teisi parandada..
        /// </summary>
        internal static string Repair_Crazy_TooDamaged {
            get {
                return ResourceManager.GetString("Repair_Crazy_TooDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} istub mutrivõtmega ja ootab katkiseid..
        /// </summary>
        internal static string Repair_DoWork {
            get {
                return ResourceManager.GetString("Repair_DoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: remondiks pole piisavalt akut..
        /// </summary>
        internal static string Repair_Repair_LowBattery {
            get {
                return ResourceManager.GetString("Repair_Repair_LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} otsib, mida parandada, kuid kedagi pole..
        /// </summary>
        internal static string Repair_Repair_NoTarget {
            get {
                return ResourceManager.GetString("Repair_Repair_NoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} üritab ennast parandada ja segab end tööriistadesse ära..
        /// </summary>
        internal static string Repair_Repair_Self {
            get {
                return ResourceManager.GetString("Repair_Repair_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} asub tööle. {1}.
        /// </summary>
        internal static string Repair_Repair_Start {
            get {
                return ResourceManager.GetString("Repair_Repair_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} töötab tavapärase programmi järgi..
        /// </summary>
        internal static string Robot_DoWork {
            get {
                return ResourceManager.GetString("Robot_DoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on juba ideaalses korras, remonti pole vaja..
        /// </summary>
        internal static string Robot_Repair_AlreadyPerfect {
            get {
                return ResourceManager.GetString("Robot_Repair_AlreadyPerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sai remonditud: terviklikkus {1} → {2}..
        /// </summary>
        internal static string Robot_Repair_Done {
            get {
                return ResourceManager.GetString("Robot_Repair_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: vigane remondimaht ({1}), olek jäi muutmata..
        /// </summary>
        internal static string Robot_Repair_InvalidAmount {
            get {
                return ResourceManager.GetString("Robot_Repair_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (#{1}) [{2}].
        /// </summary>
        internal static string Robot_ToString {
            get {
                return ResourceManager.GetString("Robot_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisatud: {0}..
        /// </summary>
        internal static string World_Added {
            get {
                return ResourceManager.GetString("World_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID {0} on juba kasutusel..
        /// </summary>
        internal static string World_DuplicateId {
            get {
                return ResourceManager.GetString("World_DuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali esmalt robot..
        /// </summary>
        internal static string World_NoRobot {
            get {
                return ResourceManager.GetString("World_NoRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali remondi sihtmärk..
        /// </summary>
        internal static string World_NoTarget {
            get {
                return ResourceManager.GetString("World_NoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ei ole laetav: tal on reaktor, aitäh..
        /// </summary>
        internal static string World_NotChargeable {
            get {
                return ResourceManager.GetString("World_NotChargeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ei oska parandada..
        /// </summary>
        internal static string World_NotRepairer {
            get {
                return ResourceManager.GetString("World_NotRepairer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ei oska skaneerida..
        /// </summary>
        internal static string World_NotScanner {
            get {
                return ResourceManager.GetString("World_NotScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eemaldatud: {0}..
        /// </summary>
        internal static string World_Removed {
            get {
                return ResourceManager.GetString("World_Removed", resourceCulture);
            }
        }
    }
}
