//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotPlanet.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotPlanet.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lae.
        /// </summary>
        public static string Btn_Charge {
            get {
                return ResourceManager.GetString("Btn_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tühjenda logi.
        /// </summary>
        public static string Btn_ClearLog {
            get {
                return ResourceManager.GetString("Btn_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hullumeelne tegevus!.
        /// </summary>
        public static string Btn_Crazy {
            get {
                return ResourceManager.GetString("Btn_Crazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eemalda valitud.
        /// </summary>
        public static string Btn_Remove {
            get {
                return ResourceManager.GetString("Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paranda.
        /// </summary>
        public static string Btn_Repair {
            get {
                return ResourceManager.GetString("Btn_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skanni.
        /// </summary>
        public static string Btn_Scan {
            get {
                return ResourceManager.GetString("Btn_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tööta.
        /// </summary>
        public static string Btn_Work {
            get {
                return ResourceManager.GetString("Btn_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kogus peab olema täisarv..
        /// </summary>
        public static string Err_Amount_NotNumber {
            get {
                return ResourceManager.GetString("Err_Amount_NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aku peab olema täisarv..
        /// </summary>
        public static string Err_Battery_NotNumber {
            get {
                return ResourceManager.GetString("Err_Battery_NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID peab olema täisarv..
        /// </summary>
        public static string Err_Id_NotNumber {
            get {
                return ResourceManager.GetString("Err_Id_NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terviklikkus peab olema täisarv..
        /// </summary>
        public static string Err_Integrity_NotNumber {
            get {
                return ResourceManager.GetString("Err_Integrity_NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali esmalt robot..
        /// </summary>
        public static string Err_No_Selection {
            get {
                return ResourceManager.GetString("Err_No_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali roboti tüüp..
        /// </summary>
        public static string Err_No_Type {
            get {
                return ResourceManager.GetString("Err_No_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tegevused.
        /// </summary>
        public static string Group_Actions {
            get {
                return ResourceManager.GetString("Group_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa robot.
        /// </summary>
        public static string Group_Add {
            get {
                return ResourceManager.GetString("Group_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üksikasjad.
        /// </summary>
        public static string Group_Details {
            get {
                return ResourceManager.GetString("Group_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robotid.
        /// </summary>
        public static string Group_List {
            get {
                return ResourceManager.GetString("Group_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logi.
        /// </summary>
        public static string Group_Log {
            get {
                return ResourceManager.GetString("Group_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aku.
        /// </summary>
        public static string Lbl_Battery {
            get {
                return ResourceManager.GetString("Lbl_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laadimiskogus.
        /// </summary>
        public static string Lbl_ChargeAmount {
            get {
                return ResourceManager.GetString("Lbl_ChargeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Lbl_Id {
            get {
                return ResourceManager.GetString("Lbl_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terviklikkus.
        /// </summary>
        public static string Lbl_Integrity {
            get {
                return ResourceManager.GetString("Lbl_Integrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi.
        /// </summary>
        public static string Lbl_Name {
            get {
                return ResourceManager.GetString("Lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remondi sihtmärk.
        /// </summary>
        public static string Lbl_RepairTarget {
            get {
                return ResourceManager.GetString("Lbl_RepairTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüüp.
        /// </summary>
        public static string Lbl_Type {
            get {
                return ResourceManager.GetString("Lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robotite planeet.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
